name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs when a new commit is pushed to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Get Bun cache directory
        id: bun-cache
        run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT
        
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.bun-cache.outputs.dir }}
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
          
      - name: Install dependencies
        run: bun install
          
      - name: Run linter
        run: bun run lint
          
      - name: Run type check
        run: bun run typecheck
          
      - name: Run tests
        run: bun test
          
      - name: Build plugin
        run: bun run build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: |
            main.js
            manifest.json
            styles.css
          if-no-files-found: error