name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Cancel in-progress runs when a new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better diff comparisons
        
      - name: Check PR title format
        run: |
          # Ensure PR title doesn't start with WIP
          if [[ "${{ github.event.pull_request.title }}" == WIP* ]]; then
            echo "::error::PR title starts with WIP. Please remove WIP when ready for review."
            exit 1
          fi
          
      - name: Check branch name
        run: |
          # Get the branch name
          BRANCH="${{ github.head_ref }}"
          
          # Check if branch follows naming convention
          if [[ ! "$BRANCH" =~ ^(feature|fix|docs|style|refactor|test|chore|setup)/.+ ]]; then
            echo "::warning::Branch name '$BRANCH' doesn't follow convention: type/description"
          fi